### PR TITLE
fix: resource booking search issues

### PR DESCRIPTION
**Pull request by eisbilir**
demo data is improved with various dates, ids, userHandles, etc..
using postman folder: `Resource Bookings > Extended Search Scenarios` after importing demo data will help to test every possible combination of search criterias.

### CODE REVIEW

**Comment by maxceem** [comment]
@eisbilir when I run `npm run local:init` I get error `importData ERROR : bulk.flatMap is not a function`, see screenshot https://monosnap.com/file/oDZZK3ycMNVaRsQ38C9AySGGM5hlHK

Do you have the same issue, or `npm run local:init` works good to you?

**Comment by eisbilir** [comment]
@maxceem it works good for me https://prnt.sc/13mx1a4

**Comment by maxceem** [comment]
my bad, I used node 10, works good with node 12

thank you @eisbilir

**Comment by eisbilir** [comment]
I had to resolve conflicts after this pull #279

**Review by maxceem — APPROVED** [review]
@eisbilir thank you resolving the conflicts with DEV.

It works good for me as per local testing. I would merge it to DEV and ask QA team to check it one more time.

**Pull request merged**
