### PR TITLE
endpoints for create/update WPP in bulk

### PR DESCRIPTION
**Pull request by eisbilir**

### CODE REVIEW

**Review by maxceem — CHANGES_REQUESTED** [review]
@eisbilir I've noticed in Swagger request for `bulk` update suppose to be array while now it's one object:

image

Otherwise works great.

**Comment by eisbilir** [comment]
@maxceem I've changed the calculation of maxPossibleDays when updating WPP here: https://github.com/topcoder-platform/taas-apis/pull/438/files#diff-804e247f8b86363db6fdd74bb6494b367edb28133e2a794ffe988522db7d3fd2R286-R287
If you didn't notice, I need you to double check if it's correct now.

**Comment by maxceem** [comment]
>  I've changed the calculation of maxPossibleDays when updating WPP here: https://github.com/topcoder-platform/taas-apis/pull/438/files#diff-804e247f8b86363db6fdd74bb6494b367edb28133e2a794ffe988522db7d3fd2R286-R287

@eisbilir great catch! Thanks for fixing that.

**Review by maxceem — APPROVED** [review]
@eisbilir all is perfect now.

**Pull request merged**
