### PR TITLE
Split email template and update text

### PR DESCRIPTION
**Pull request by xxcxy**
1. rendered HTML file url: https://drive.google.com/file/d/1va8u8Qslr8cLRGChE3sqbV_sl1XNr_v4/view?usp=sharing
2. screenshot:
  - https://monosnap.com/file/nwijnsjLEq90UHcXUPMZDsLo7Y65mS
  - https://monosnap.com/file/zbbMv4v9wsj6VSs62XEvUa7r6Kc8Eb
  - https://monosnap.com/file/YEeSoF0zhImKw0SWiDRwTI30ksh15e
  - https://monosnap.com/file/hiqVrAxnthnLmrvVAzJ7TOyheQ2zXE
  - https://monosnap.com/file/IyL5o8U5hyeKJWKSDirTSa4hytP1cC
  - https://monosnap.com/file/vAXTtQeQX9aiV5yfejVKHVyATrx0ON
  - https://monosnap.com/file/E63qAi2AiMOS94rCQfuBEATbEx5xhN
  - https://monosnap.com/file/FYmgAwx1lmc0qABvRTbML5rDHaHx17
  - https://monosnap.com/file/brjKXiigWKUzDg31oWlwESZhmsVlNY
  - https://monosnap.com/file/mQe4U4qoa9z25bEIjFfUNzNiLwKCeJ
 3. set these vars in env:
   - NOTIFICATION_CLIENT_VIEWED_PROFILE_SENDGRID_TEMPLATE_ID=1
   - NOTIFICATION_REVIEW_CANDIDATES_SENDGRID_TEMPLATE_ID=2
   - NOTIFICATION_CUSTOMER_INTERVIEW_COMING_UP_SENDGRID_TEMPLATE_ID=3
   - NOTIFICATION_MEMBER_INTERVIEW_COMING_UP_SENDGRID_TEMPLATE_ID=4
   - NOTIFICATION_INTERVIEW_COMPLETE_SENDGRID_TEMPLATE_ID=5
   - NOTIFICATION_POST_INTERVIEW_ACTION_SENDGRID_TEMPLATE_ID=6
   - NOTIFICATION_UPCOMING_RESOURCE_BOOKING_EXPIRATION_SENDGRID_TEMPLATE_ID=7
   - NOTIFICATION_NEW_TEAM_CREATED_SENDGRID_TEMPLATE_ID=8
   - NOTIFICATION_NEW_JOB_ADDED_SENDGRID_TEMPLATE_ID=9
   - NOTIFICATION_RESOURCE_BOOKING_PLACED_SENDGRID_TEMPLATE_ID=10

### CODE REVIEW

**Comment by xxcxy** [comment]
new verification file: https://drive.google.com/file/d/1zpfy7BDxcwFEY0W0t2UUJRh21vNi_Xfm/view?usp=sharing

**Review by maxceem — CHANGES_REQUESTED** [review]
@xxcxy Here are small mismatches I found:

- Can we also update demo script README and mention that we have to define 12 env variables for email templates, otherwise it would not work https://monosnap.com/file/xmmJcjeYWh6a71iAD9mQZkm2rHW7Gh
- `02` no need space https://monosnap.com/file/p2P1Yo8hhY8jHYBt4ajijWdSAz9uoz
- `03` 
    - missing link `Review Your Candidates` below the table https://monosnap.com/file/XyyAtxIUHcOoq7dPVEYjEMYefAD26X
    - no need space https://monosnap.com/file/OLVMyAv9xLtZLrWhTyfNAsU3dvTXfH
- `04` 
    - should be a capital letter "I" https://monosnap.com/file/E3TpwxTw30JZYa53klWxfLI1n988iS
    - missing link `Candidate resume and profile` below the table, LInk to the interviews page, same like in table https://platform.topcoder-dev.com/taas/myteams/18673/positions/20e75533-33f6-4aa7-8561-318a55e6b0ce/candidates/interviews
    - no need space https://monosnap.com/file/g01ac6TmHLotOt6uzNHhpXACLkQxmY
- `05` missing link `Take action on your candidates` which should lead the interviews tab, same like in table https://platform.topcoder-dev.com/taas/myteams/111/positions/36dad9f2-98ed-4d3a-9ea7-2cd3d0f8a51a/candidates/interviews    
- `06`
   - missing `Reminder:` word https://monosnap.com/file/cOHsar3W8cBe4KstG8MWZS1ecL5M5e
   - missing link `Take action on your candidates` which should lead to the same place as link from table https://platform.topcoder-dev.com/taas/myteams/111/positions/a8adb1f8-a6ee-48b1-8661-33bd851b726e/candidates/interviews
- `07` space is not needed https://monosnap.com/file/UGgIF43wP8EeaU6Z1omjfNTnaspOrF
- `08`
   - no need space https://monosnap.com/file/fxdx6Yx6CDSHyqZFVUMYssnjMb278o
   - `here` should be the same link as `Teams` https://monosnap.com/file/TNlX2H7u8KvqAd61doixBjV1prDTDw
- `Emails for Members - 01` - `Open Applications` should be a link to https://platform.topcoder-dev.com/earn/my-gigs?status=Open%20Applications (URL path should come from API for DEV/PROD)
- `Emails for Members - 02` - `Applications` should be a link to https://platform.topcoder-dev.com/earn/my-gigs?status=Active%20Gigs (URL path should come from API for DEV/PROD)

**Comment by maxceem** [comment]
@xxcxy one more thing, we don't have to pass `description` anymore for any email. For example here https://github.com/topcoder-platform/taas-apis/blob/dev/src/services/NotificationsSchedulerService.js#L335 and in other places, as we include it directly into email now.

**Comment by xxcxy** [comment]
All done.
btw: I think the workload exceeds $100.

**Review by maxceem — APPROVED** [review]
Thank you @xxcxy all works perfectly now.

**Comment by maxceem** [comment]
> btw: I think the workload exceeds $100.

@xxcxy Sure, would be $150 fine + $20 for padding? Or, please, let me know how would you evaluate.

**Comment by xxcxy** [comment]
> > btw: I think the workload exceeds $100.
> 
> @xxcxy Sure, would be $150 fine + $20 for padding? Or, please, let me know how would you evaluate.

It's fine. Thank you.

**Pull request merged**
