### PR TITLE
Send Weekly Surveys

### PR DESCRIPTION
**Pull request by yoution**
@maxceem please merge

### CODE REVIEW

**Comment by yoution** [comment]
@maxceem please review

**Review by maxceem — CHANGES_REQUESTED** [review]
@yoution 

I'm trying to test sending survey locally, though I'm getting errors like these https://monosnap.com/file/5J7Z6MSYJGuT21D8DpgzXFzWxsqHld
do you have some idea what could be the reason?
I'm using config from the validation guide.

Also, regarding this update in code I'm not sure how this would help, as for me to fix this issue ` "As per logs in Run 02, encountered "ERROR : Error : socket hang up" during the sending of first survey. There's no exception handler and theres no way to recover (other than to restart or reset cron)."` we have to wrap each of `await partiallyUpdateWorkPeriod` inside additional `try {} catch () {}` so we catch any error which happens during updating work period too.

image

**Comment by yoution** [comment]
@maxceem can we change the date format to `d/m/yyyy` to `dd/mm/yyyy`

**Comment by maxceem** [comment]
@yoution actually this format we have been already using for such surveys, so I don’t think we can change it. Any issues with it?

**Comment by yoution** [comment]
you can change to `dd/mm/yyyy` firstly, I will debug the code, wait a moment

**Comment by maxceem** [comment]
Thanks, I’ll check tomorrow morning using this format, though ideally we need to use existent format.

**Comment by yoution** [comment]
image
I can not reproduce the error locally, 
https://github.com/yoution/taas-apis/blob/feature/weekly-surveys/src/common/surveyMonkey.js#L48, is this line?

**Comment by yoution** [comment]
@maxceem  please ignore the format error, maybe the `surveyId` is not correct?
image

**Comment by yoution** [comment]
@maxceem 
`WEEKLY_SURVEY_BASE_URL=https://api.surveymonkey.net/v3
WEEKLY_SURVEY_JWT_TOKEN=a4GsFQe--qWxKkw3JrdCdpy5UPjc3MWOgWu0WxHGC4w6UObeuG.Iq1zNXheBFH6srWmcrDg1FtusK3E12X8L-G8HTPUKVQ2YfOwTZOm0zAbpvgY6pzKZIXQcF7V.Agti
WEEKLY_SURVEY_SURVEY_ID=309903027
WEEKLY_SURVEY_SURVEY_MASTER_COLLECTOR_ID=407893109
WEEKLY_SURVEY_SURVEY_CONTACT_GROUP_ID=213276964
WEEKLY_SURVEY_SURVEY_MASTER_MESSAGE_ID=91076799`
please use these `env`

**Comment by yoution** [comment]
@maxceem for `socket hang up error`, maybe 
image
the `tc-bus-api` should update

**Comment by maxceem** [comment]
@yoution your config you shared above helped me, thanks! (btw, I've removed it from the comment)

The only one thing left: the app should not crash is some error happens.
For now, if some error happens during `partiallyUpdateWorkPeriod()` the whole app crashes.
To reproduce the issue I throw error:
```js
async function partiallyUpdateWorkPeriod (currentUser, id, data) {
  throw new Error('some error during WP update')
  return updateWorkPeriod(currentUser, id, data)
}
```

image

So what should be done to prevent this I think:
1. Don't make this change to the code:

    I'm not sure why this change was done, if there is any reason for this, please let me know.
    
    image

2. Each `partiallyUpdateWorkPeriod()` during sending serveys should be wrapped into `try {} catch` so error happened during `partiallyUpdateWorkPeriod` should be catched and just logged by logger. But don't break the whole app.

**Comment by yoution** [comment]
@maxceem for 1. why did I change the code, because when error happened in `partiallyUpdateWorkPeriod `,
but actually, the survery has been sent successfully, when it will go into the error, can set the `sendSurvey: false` and `sentSurveyError: e`
2. I will fix soon

**Review by maxceem — APPROVED** [review]
Thanks for the quick updates @yoution all works good now.

**Pull request merged**
