### PR TITLE
fix: additional payments

### PR DESCRIPTION
**Pull request by narekcat**

### CODE REVIEW

**Review by maxceem — CHANGES_REQUESTED** [review]
@narekcat sorry, I forgot to mention one more thing.

If we process a payment with `days = 0` then `amount` is required to be provided and it must be more than `0`. Otherwise, if I try to process a payment with `days = 0` there would be an internal server error:

image

So if we are trying to create a payment with `days = 0` we should validate that `amount` is provided and it's more than `0` otherwise return error: `"amount" has to be provided when processing additional payment for 0 days`. It's preferable to use Joi validation for this if possible https://github.com/topcoder-platform/taas-apis/blob/dev/src/services/ResourceBookingService.js#L358-L365.

Could you please add this validation? I would increase payment for the task to $30.

**Comment by narekcat** [comment]
Hi @maxceem . Ok, I am already working on it.

**Comment by narekcat** [comment]
@maxceem . I have fixed that issue, please check it again.

**Review by maxceem — CHANGES_REQUESTED** [review]
@narekcat looks like it doesn't work:

image

Let me clarify.

If `days` and/or `amount` is not provided - it's calculated automatically. This was already implemented.

The only thing we are changing now, is that we allow providing `days = 0` (before we didn't allow this). So now we only should allow providing `days = 0`, but if we provide `days = 0` then we should require providing `amount > 0` because when `days =0` we cannot calculate `amount` automatically anymore.

**Comment by narekcat** [comment]
@maxceem , I have fixed that.

**Review by maxceem — APPROVED** [review]
@narekcat thanks for the quick update, works well now.

**Pull request merged**
